# Generated by Django 6.0 on 2025-12-17 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_message_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='system_instruction',
            field=models.TextField(default='You are a helpful AI assistant. Answer concisely and accurately.'),
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='title',
            field=models.CharField(default='New Chat', max_length=255),
        ),
    ]
