# Generated by Django 6.0 on 2025-12-17 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_chatsession_system_instruction_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatsession',
            name='system_instruction',
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='title',
            field=models.CharField(default='New Chat', max_length=200),
        ),
    ]
